# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Qi's Page
email: wq.levi@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  This is the personal webpage of Qi, who's doing a PhD. in Max Planck Institute in TÃ¼bingen. The website will be including reseach projects,
  technical blogs and other interesting contents. Stay tuned ;)
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://wqlevi.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: LeviWQ1
github_username:  wqlevi

# Build settings
remote_theme: just-the-docs/just-the-docs

color_scheme: dark
markdown: kramdown
plugins:
  - jekyll-feed

    
# color_scheme: dark
# footnote
last_edit_timestamp: true # show or hide edit time - page must have `last_modified_date` defined in the frontmatter
last_edit_time_format: "%b %e %Y at %I:%M %p" # uses ruby's time format: https://ruby-doc.org/stdlib-2.7.0/libdoc/time/rdoc/Time.html

